async function fail(): Promise<Output> {
  throw new Error("oopsie!");
}
